services:
  backend:
    build: ./backend
    container_name: currencies-backend
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
    networks:
      - currencies

  frontend:
    build: ./frontend
    container_name: currencies-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - currencies
      
networks:
  currencies:
    name: currencies-network
